name: deployer
base: core18
version: '0.1.6'
summary: Deployer app deployment assistant on Google Play and a little bit more.
description: |
  * Web interface for generate access token Oauth 2.0
  * Upload to Google Play production, internal... (Play Developer API)
  * Newsletter after upload build in Google Play (Gmail API)
  * Connect webhooks after upload test or prod (Slack API)
  * CHANGELOG.md generation based git history (Thymeleaf)

grade: stable
confinement: strict

parts:
  deployer:

    plugin: gradle
    gradle-output-dir: build/libs
    gradle-options: [bootJar]
    source: https://github.com/keygenqt/deployer.git
    source-type: git
    source-tag: master
    build-environment:
      - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      - PATH: $JAVA_HOME/jre/bin:$PATH

    build-packages:
      - openjdk-11-jdk
      - openjdk-11-jre
      - ca-certificates
      - ca-certificates-java

    stage-packages:
      - openjdk-11-jre
      - ca-certificates
      - ca-certificates-java
      - git

apps:
  deployer:
    command: java -jar $SNAP/jar/deployer.jar
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - network-bind